version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - ./backend/app:/app
      - ./backend/db:/app/db  # SQLiteデータベースファイルの永続化
    environment:
      - API_URL=${API_URL}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modules をコンテナ内にのみ保持
    stdin_open: true
